#!/usr/bin/env bash
# Tests for docs/validate.sh (generated by project_setup.sh)

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/test_helpers.sh"

print_section "validate.sh tests"

# Helper: run setup in the current sandbox to get a clean environment
run_setup() {
  bash project_setup.sh >/dev/null 2>&1
}

# ── Test 1: Passes on clean setup ──

setup_sandbox
run_setup
bash docs/validate.sh >/dev/null 2>&1
assert_exit_code $? 0 "Passes on clean setup"
teardown_sandbox

# ── Test 2: Detects missing overview.md ──

setup_sandbox
run_setup
rm docs/arch/overview.md
output=$(bash docs/validate.sh 2>&1)
ec=$?
assert_exit_code "$ec" 1 "Detects missing overview.md (exit code)"
assert_output_contains "$output" "MISSING" \
  "Detects missing overview.md (MISSING in output)"
teardown_sandbox

# ── Test 3: Detects unlisted .md file in docs/arch/ ──

setup_sandbox
run_setup
echo "# Backend" > docs/arch/backend.md
output=$(bash docs/validate.sh 2>&1)
ec=$?
assert_exit_code "$ec" 1 "Detects unlisted file in docs/arch/ (exit code)"
assert_output_contains "$output" "NOT IN OVERVIEW" \
  "Detects unlisted file in docs/arch/ (NOT IN OVERVIEW)"
teardown_sandbox

# ── Test 4: Detects unlisted .md file in docs/tasks/ ──

setup_sandbox
run_setup
echo "# Some task" > docs/tasks/some-task.md
output=$(bash docs/validate.sh 2>&1)
ec=$?
assert_exit_code "$ec" 1 "Detects unlisted file in docs/tasks/ (exit code)"
assert_output_contains "$output" "some-task.md" \
  "Detects unlisted file in docs/tasks/ (mentions filename)"
teardown_sandbox

# ── Test 5: Detects unlisted .md file in docs/ref/ ──

setup_sandbox
run_setup
echo "# API notes" > docs/ref/api-notes.md
output=$(bash docs/validate.sh 2>&1)
ec=$?
assert_exit_code "$ec" 1 "Detects unlisted file in docs/ref/ (exit code)"
assert_output_contains "$output" "api-notes.md" \
  "Detects unlisted file in docs/ref/ (mentions filename)"
teardown_sandbox

# ── Test 6: Detects unlisted subdirectory ──

setup_sandbox
run_setup
mkdir -p docs/arch/payments
echo "# Payments Overview" > docs/arch/payments/overview.md
output=$(bash docs/validate.sh 2>&1)
ec=$?
assert_exit_code "$ec" 1 "Detects unlisted subdirectory (exit code)"
assert_output_contains "$output" "payments" \
  "Detects unlisted subdirectory (mentions dir name)"
teardown_sandbox

# ── Test 7: Ignores TEMPLATE.md ──

setup_sandbox
run_setup
bash docs/validate.sh >/dev/null 2>&1
assert_exit_code $? 0 "Ignores TEMPLATE.md (tasks/TEMPLATE.md present, still passes)"
teardown_sandbox

# ── Test 8: Ignores GROUP_OVERVIEW_TEMPLATE.md ──

setup_sandbox
run_setup
bash docs/validate.sh >/dev/null 2>&1
assert_exit_code $? 0 "Ignores GROUP_OVERVIEW_TEMPLATE.md (present, still passes)"
teardown_sandbox

# ── Test 9: Ignores archive/ subdirectory ──

setup_sandbox
run_setup
mkdir -p docs/tasks/archive
echo "# Archived" > docs/tasks/archive/old-task.md
bash docs/validate.sh >/dev/null 2>&1
assert_exit_code $? 0 "Ignores archive/ subdirectory"
teardown_sandbox

# ── Test 10: Recursive validation of subdirectories ──

setup_sandbox
run_setup
mkdir -p docs/tasks/backend
echo "# Backend Tasks" > docs/tasks/backend/overview.md
echo "# Unlisted task" > docs/tasks/backend/task.md
# Also list backend in the parent overview so that part passes
echo "| backend | In progress | -- | Backend tasks |" >> docs/tasks/overview.md
output=$(bash docs/validate.sh 2>&1)
ec=$?
assert_exit_code "$ec" 1 "Recursive validation catches unlisted file in subdir (exit code)"
assert_output_contains "$output" "task.md" \
  "Recursive validation mentions the unlisted file"
teardown_sandbox

# ── Test 11: Reports correct error count ──

setup_sandbox
run_setup
echo "# File A" > docs/arch/a.md
echo "# File B" > docs/arch/b.md
echo "# File C" > docs/ref/c.md
output=$(bash docs/validate.sh 2>&1)
ec=$?
assert_exit_code "$ec" 1 "Reports errors when multiple files unlisted (exit code)"
assert_output_contains "$output" "3 inconsistencies found" \
  "Reports correct error count (3)"
teardown_sandbox

# ── Test 12: Passes when file is properly listed ──

setup_sandbox
run_setup
echo "# Backend" > docs/arch/backend.md
echo "| Backend | [backend.md](backend.md) | Single file | REST API |" >> docs/arch/overview.md
bash docs/validate.sh >/dev/null 2>&1
assert_exit_code $? 0 "Passes when file is properly listed in overview"
teardown_sandbox

# ── Test 13: Handles non-existent root dir gracefully ──

setup_sandbox
run_setup
rm -rf docs/arch
output=$(bash docs/validate.sh 2>&1)
ec=$?
# Should still run and check the remaining directories
assert_exit_code "$ec" 0 "Handles non-existent root dir gracefully (still runs)"
assert_output_contains "$output" "All overview.md files are in sync" \
  "Reports success for remaining valid dirs"
teardown_sandbox
